title: AMP for Email
description: wg-amp4email Working Group is responsible for the development and maintenance of the AMP for Email specification and related features.
facilitator:
  login: choumx
  name: William Chou
members:
  - login: cathyma123
    name: Cathy Ma
  - login: choumx
    name: William Chou
  - login: fstanis
    name: Filip Stanis
  - login: jasti
    name: Vamsee Jasti
  - login: johnbarr
    name: John Barr
  - login: kaewka
    name: Thanawat Kaewka
  - login: latrekc
    name: Stanislav Tugovikov
